Fix failing docs build on crates.io
blas-lapack-rs/openblas-src pull request #109
Opened 2024-01-06 10:13 UTC by HenrikJStromberg

Suppress build on crates.io by checking DOCS_RS to circumvent failing of building docs without internet connection as is the situation on crates.io

2024-01-11 07:32 UTC, HenrikJStromberg commented
It looks like we are having a conflict between your deployment pipeline and crates.io. Does your test environment set DOCS_RS which I am using to detect crates.io?

2024-11-26 20:11 UTC, Dirreke requested changes

2024-11-26 20:11 UTC, Dirreke commented on openblas-src/build.rs
> +    if !env::var("DOCS_RS").is_ok() {
```suggestion
    if env::var("DOCS_RS").is_ok() {
```

2024-11-27 16:19 UTC, Dirreke commented
Included by #125

2024-11-27 16:19 UTC, closed without merging