Add DYN_ARCH/USE_THREADS/USE_OPENMP features on linux
blas-lapack-rs/openblas-src pull request #72
Opened 2021-04-28 09:37 UTC by cassiersg

These features were supported by the build crate, but not exposed.

I picked a default value for NUM_THREADS when USE_THREADS is set, as I see no way to have this configured through features.

2021-07-10 05:24 UTC, IvanUkhov commented
This probably should be done together with #73.

2024-12-01 00:05 UTC, Dirreke commented
@cassiersg Hi, would you still like to rebase it?

2024-12-08 14:42 UTC, cassiersg commented
@Dirreke done

2024-12-08 16:48 UTC, Dirreke requested changes

2024-12-08 16:48 UTC, Dirreke commented on openblas-build/src/build.rs
> +            args.push("NUM_THREADS=256".into());
I’m not certain if it’s necessary . After setting use_thread, will OpenBlas makefile script detect num_thread atomically?

2024-12-08 16:48 UTC, Dirreke commented on openblas-src/build.rs
> +        cfg.no_shared = true;
I believe the variable name should be dynamic_arch. Additionally, please move these codes to line 145.

2024-12-08 16:48 UTC, Dirreke commented
Close #106

2024-12-08 18:11 UTC, cassiersg commented
I'm unfortunately not using openblas anymore, and I barely remember why I did this PR. As for the `NUM_THREADS`, I'm not sure to remember all the details (this is getting quite old). If I remember correctly, `NUM_THREADS` is an upper-bound on the number of threads that will be selected at run-time, and the default openblas build script was defaulting to something too low (probably I was compiling on a small machine, then running on a much larger one).

Since I'm not able to help, I'm gonna close this PR and let anybody interested who has more time available finish that work.

2024-12-08 18:11 UTC, closed without merging